version: '3'

networks:
  default:
    driver: bridge

services:
  mysql8:
    image: 'mysql:8'
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    networks:
      - default
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql8
      - MYSQL_DATABASE=test
